# Lista de palavras
lista_palavras = [
"abacaxi", "abelha", "abertura", "abismo", "acampar", "achar", "acidente", "acionar", "acordar", "adeus",
"adiar", "adorar", "adubo", "aeroporto", "afastar", "afiar", "afirmar", "agir", "agora", "aguia",
"bala", "bambu", "bancada", "barco", "batata", "beijo", "belo", "bola", "borboleta", "bravo",
"cachorro", "cadeira", "caminhar", "canto", "carro", "casa", "cevada", "chocolate", "chuva", "ciclone",
"dado", "danca", "degrau", "dentro", "desejo", "deus", "diamante", "dinheiro", "direito", "doce",
"elefante", "elevar", "embarcar", "embuste", "energia", "enigma", "enrolar", "esfera", "espada", "espelho",
"faca", "falar", "fardo", "farinha", "fechar", "felicidade", "ferida", "ferro", "festa", "fico",
"garfo", "gato", "gelado", "gelatina", "gemada", "geral", "gerar", "girafa", "globo", "grandeza",
"harpa", "heroi", "humano", "hamburguer", "hora", "homem", "honestidade", "hospedar", "hospital", "hurra",
"igreja", "ilha", "imagem", "impresso", "ingresso", "iniciar", "inseto", "interno", "inverno", "inveja",
"jabuticaba", "jardim", "joelho", "jogar", "jovem", "juba", "judoca", "julgar", "jurar", "justo",
"kiwi", "kombi", "kung fu", "ketchup", "kit", "karma", "karaoke", "kilo", "kaiser", "kirsch",
"lindo", "livro", "lua", "luar", "luz", "lamentar", "laranja", "leal", "leao", "lenha",
"maquina", "mais", "mala", "mar", "margarida", "mel", "mesa", "meteoro", "montanha", "mundo",
"navio", "neve", "ninho", "noite", "noticia", "novo", "ninho", "nublado", "nacional", "nuvem",
"ocasiao", "ocelote", "oito", "olho", "oliva", "onda", "organico", "orquidea", "ostra", "ouro",
"pato", "paz", "pente", "piano", "picles", "pimenta", "plano", "porto", "primavera", "prato",
"quarto", "quasar", "quem", "querida", "quiche", "quilo", "quina", "quintal", "quiosque", "quieto",
"raiz", "ramo", "rato", "rebento", "reformar", "refresco", "reggae", "reino", "relogio", "resposta",
"sabor", "sacada", "sadio", "safo", "salada", "salgado", "salsicha", "saque", "sauna", "saxofone",
"tambor", "tampa", "tangerina", "tanque", "tardio", "tatu", "teatro", "tempestade", "templo", "tenis",
"umido", "unha", "uniforme", "unico", "universo", "urbanidade", "urgencia", "urso", "urze", "usina",
"vaca", "vagar", "vale", "valvula", "vanilla", "vapor", "vasilha", "vastidao", "vazio", "veado",
"venda", "vento", "verao", "verde", "vestir", "vetor", "viagem", "vibrar", "vicio", "vida",
"xale", "xarope", "xaxim", "xerife", "xerox", "xiita", "xilogravura", "xingar", "xisto", "xixi",
"yakisoba", "yoga", "yard", "yoga", "yorkshire", "yuan", "yakisoba", "yoga", "youtuber", "yule",
"zarpar", "zangar", "zap", "zarolho", "zarpar", "zebra", "zelador", "zelo", "zenite", "zero",
"ziguezague", "zombar", "zonzo", "zorra", "zumbido", "zumbi", "zunido", "zurro", "zunido", "zangado"
]
